Update sum, mean and other functions to be used with slidingWindow
composewell/streamly-statistics pull request #16
Opened 2021-12-28 20:25 UTC by specdrake

2021-12-29 02:35 UTC, harendra-kumar commented on src/Streamly/Statistics.hs
> +          Just old -> s + a - old
Please see https://en.wikipedia.org/wiki/Kahan_summation_algorithm .

2021-12-29 02:38 UTC, harendra-kumar commented on src/Streamly/Statistics.hs
> +          Just old -> s + a - old
What you have written above can be renamed to `sumInt`, and the input type can be generalized to `Integral a`. That will fix https://github.com/composewell/streamly-statistics/issues/9 .

2021-12-29 02:56 UTC, harendra-kumar commented on src/Streamly/Statistics.hs
> +          Just old -> s + a - old
Or maybe we can just generalize the Kahan summation to type `a` to include Integral types as well. GHC may simplify it automatically, we can check the generated core.

2021-12-29 02:59 UTC, harendra-kumar commented on src/Streamly/Statistics.hs
> +mean = teeMean sum
Write a fold that just computes the window size i.e. just increment by 1 on seeing a Nothing in the second element of tuple. Then we can just use `Fold.teeWith (/) sum windowSize` to get the mean.

2021-12-29 10:18 UTC, harendra-kumar commented on src/Streamly/Statistics.hs
> +sumInt :: MonadIO m => Fold m (Double, Maybe Double) Double
`sumInt` operating on `Double`?

The signature should be: `sumInt :: MonadIO m => Fold m (a, Maybe a) a`

2021-12-29 10:20 UTC, harendra-kumar commented on src/Streamly/Statistics.hs
> +windowSize :: MonadIO m => Fold m (Double, Maybe Double) Double
The type does not have to be `Double`, it could be any type `a`.

2021-12-29 10:23 UTC, harendra-kumar commented on src/Streamly/Statistics.hs
> +  step w x@(a, ma) =
`x` and `a` are unused, this will generate warnings.

2021-12-29 10:24 UTC, harendra-kumar commented on src/Streamly/Statistics.hs
> +  initial = 0 :: Double
Window size cannot be `Double`, it has to be an integral type, `Int` would be fine.

2021-12-29 10:25 UTC, harendra-kumar commented on src/Streamly/Statistics.hs
> +mean = Fold.teeWith (/) sum windowSize
You can use `fromIntegral` to convert windowSize to Double.

2021-12-29 10:34 UTC, specdrake commented on src/Streamly/Statistics.hs
> +sumInt :: MonadIO m => Fold m (Double, Maybe Double) Double
What should be the initial value of the state? I tried using `mempty :: a` but it could not deduce `Monoid` instance of `a1`(?):
```Could not deduce (Monoid a1) arising from a use of ‘mempty’
  from the context: (MonadIO m, Monoid a, Num a)
    bound by the type signature for:
               sumInt :: forall (m :: * -> *) a.
                         (MonadIO m, Monoid a, Num a) =>
                         Fold m (a, Maybe a) a```

2021-12-29 10:38 UTC, harendra-kumar commented on src/Streamly/Statistics.hs
> +sumInt :: MonadIO m => Fold m (Double, Maybe Double) Double
Use `0 :: a`. You will have to use `forall m a.` in the signature and `LANGUAGE ScopedTypeVariables` to get the type `a` in the scope of the function body.

2021-12-29 11:32 UTC, harendra-kumar commented on benchmark/Main.hs
> +            , benchWithFold numElements "mean (window size 1000)" (Ring.slidingWindow 1000 Statistics.mean)
Lines are too long.

2021-12-29 11:36 UTC, harendra-kumar requested changes
We do not need the `finite` bgroup any more.

2021-12-29 11:42 UTC, harendra-kumar commented on src/Streamly/Statistics.hs
> +--   (fmap (fromIntegral . P.min w) Fold.length)
Why is this commented out? Why not remove?

2021-12-29 14:09 UTC, harendra-kumar requested changes
There are a few bugs in this change, this means that we do not have good tests.

2021-12-30 10:10 UTC, specdrake commented
Can this be merged?

2021-12-30 13:01 UTC, merged