Add bound to streamly version
composewell/streamly-statistics pull request #36
Opened 2022-03-26 12:55 UTC by rnjtranjan

2022-03-26 18:38 UTC, harendra-kumar commented
The title of the PR and commit contents do not seem to match.

2022-03-26 18:39 UTC, harendra-kumar commented
Can you make two separate commits or two separate PRs?

2022-03-28 10:04 UTC, harendra-kumar requested changes

2022-03-28 10:04 UTC, harendra-kumar commented on streamly-statistics.cabal
> +                       , streamly >= 0.8.1 && < 0.9
You can rebase and remove these changes.

2022-03-28 10:04 UTC, harendra-kumar commented on src/Streamly/Statistics.hs
> +    Fold.concatMap (Fold.foldl' (ewmaStep k))  (Fold.take n Fold.mean)
Can you put these refactoring changes in a separate commit?

2022-03-28 10:04 UTC, harendra-kumar commented on src/Streamly/Statistics.hs
> +bubbleAsc idx cmp arr = do
We can add this in streamly mutable array module itself, in the mutable algorithms section.

2022-03-29 14:42 UTC, rnjtranjan commented
new PR is created : https://github.com/composewell/streamly/pull/1570

2022-03-29 14:42 UTC, closed without merging