Remove functions implemented in Streamly package
composewell/streamly-statistics pull request #39
Opened 2022-04-18 08:26 UTC by rnjtranjan

2022-04-18 08:27 UTC, rnjtranjan commented
Fixes : https://github.com/composewell/streamly-statistics/issues/37

2022-04-19 11:24 UTC, harendra-kumar requested changes

2022-04-19 11:24 UTC, harendra-kumar commented on src/Streamly/Statistics.hs
>  noSlide f = Fold.lmap (, Nothing) f
Remove this and use `cumulative`.

2022-04-19 11:24 UTC, harendra-kumar commented on src/Streamly/Statistics.hs
> -mean = Fold.teeWith (/) sum length
Define this as `Window.mean` to retain the documentation here which is more elaborate than the doc in streamly.

2022-04-20 11:33 UTC, merged