Deduplicate Fold Scan benchmarks
composewell/streamly-statistics pull request #59
Opened 2022-07-11 06:40 UTC by rnjtranjan

2022-07-11 06:41 UTC, rnjtranjan commented
fixes:https://github.com/composewell/streamly-statistics/issues/56

2022-07-18 06:36 UTC, harendra-kumar requested changes

2022-07-18 06:36 UTC, harendra-kumar commented on benchmark/Main.hs
> +    , bgroup "scan" $ runBenchMarks benchWithPostscan benchWithFoldInt
benchWithFoldInt is being used in scan benchmarks as well. It creates two problems, (1) fold benchmarks are being run under scan benchmarks, (2) fold benchmarks are being run twice.

There are only two benchmarks using benchWithFoldInt, instead of passing it in the common function runBenchmarks we can just run those two benchmarks separately.

2022-07-18 07:48 UTC, rnjtranjan commented on benchmark/Main.hs
> +
nope.

2022-07-19 07:08 UTC, harendra-kumar requested changes
Streamly bounds need to be changed in the cabal file.

2022-07-19 07:08 UTC, harendra-kumar commented on benchmark/Main.hs
> +runBenchmarks fDouble =
`runBenchmarks` => `mkBenchmarks` as it does not run them.
fDouble => mkBench

2023-04-19 04:01 UTC, merged