Update min/max/range folds to use slidingWindow
composewell/streamly-statistics pull request #8
Opened 2021-12-24 09:34 UTC by specdrake

fixes issue #5 

The benchmarks also need be updated as the types have changed.

2021-12-25 02:30 UTC, harendra-kumar requested changes

2021-12-25 02:30 UTC, harendra-kumar commented on src/Streamly/Statistics.hs
> +  extract (Tuple3' _ _ q) = return $ snd $ fromMaybe (0, 1 / 0) $ DQ.head q
Instead of `1 / 0` we can change it to `error "min: Empty stream"`. That will also allow us to change the type from `Double` to `a` in the signature, change that too. May need to add appropriate constraints. Change the type in max and range as well.

2021-12-25 08:58 UTC, harendra-kumar commented on streamly-statistics.cabal
> +                     , streamly
Why did you remove the version bound?

2021-12-25 09:00 UTC, harendra-kumar commented on cabal.project
> +  location: git@github.com:composewell/streamly.git
Add `tag: master` at least, to be explicit what we are picking.

2021-12-25 09:02 UTC, specdrake commented on streamly-statistics.cabal
> +                     , streamly
In order to use `slidingWindow` in the tests

2021-12-25 13:36 UTC, harendra-kumar commented on streamly-statistics.cabal
> +                     , streamly
You do not need to remove it for that. Did you get some error if you do not remove? The version on the master branch is 0.8.1.1.

2021-12-25 14:02 UTC, specdrake commented on streamly-statistics.cabal
> +                     , streamly
I had not added git repo in the ``cabal.project`` and then I removed the version. Fixed it.

2021-12-26 03:25 UTC, harendra-kumar commented
Closing and reopening the PR, hopefully that will fix the CI issue.

2021-12-26 03:28 UTC, harendra-kumar commented
@specdrake I am closing this, we will create a new PR so that CIs can run.

2021-12-26 03:28 UTC, closed without merging